import React from 'react'
import '../styles/globals.css'
import Head from 'next/head';
import './tw.css';

function MyApp({Component, pageProps}) {
    return (
        <React.Fragment>
            <Head>
                <title>Tiny Teacher</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Component {...pageProps} />
        </React.Fragment>
    )
}

export default MyApp
