// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	ID          *string   `json:"id"`
	Title       *string   `json:"title"`
	Description *string   `json:"description"`
	Date        *string   `json:"date"`
	Pictures    []*string `json:"pictures"`
}

type BlogInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Date        *string `json:"date"`
}
